name: Build TypeScript

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc index.ts --outDir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-js
          path: dist/index.js
